sudo: required
language: go
go:
- 1.9
before_install:
- sudo apt-get install zip
- go get github.com/tools/godep
- go get -d github.com/stretchr/testify/assert
install:
- godep restore
script:
- go test -v ./...
- mkdir linux_amd64
- mkdir windows_amd64
- go build  -o ./linux_amd64/blobporter github.com/Azure/blobporter
- export GOOS=windows
- go build  -o ./windows_amd64/BlobPorter.exe github.com/Azure/blobporter
- cp LICENSE ./linux_amd64/LICENSE
- cp LICENSE ./windows_amd64/LICENSE
- md5sum ./linux_amd64/blobporter > ./linux_amd64/blobporter.md5
- md5sum ./windows_amd64/BlobPorter.exe > ./windows_amd64/BlobPorter.exe.md5
- tar cvzf bp_linux.tar.gz linux_amd64
- zip bp_windows.zip ./windows_amd64/*
- bash inttest.sh inttest
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OluucIYf78l/1cMQq5MvJxGdwXS1tSxingFi9mS9onI7RPK3qXdUWY1AHxd3xlJo4vjAlPwSA4NREm8k0zcq3tTtJOVsbREoZpa7Dhbn8zkJlVuurDK15HAlU1m0F2zo1LvlNGjulQj+MF/Tk676kVtRZqd8KQ3ivTk7IkL5Q5/uMnp8/gYtHWfJZiVdVznqf+enel4ghH1zDc1a6W/SkuTTfP2lmkzJrit4H1YIzOcW+DDOAuAqmgOJPFZdfQs3kKwCEzcXVKjUMe+iiyO0yNfvtmT1QqyI48VC65y/3sPXKWYBA40O0VZ8vAQtwV2IDdYwSk1X5dqgU5U7vnrMYogyF/x5PFkBdbfALJFIZQZf07rPeVjuX6l5uskf4i3TN+bHyRElvnYshLlN9QTQkoVyHHLtoH2BCbnZhPL81S9nfIbQgp5ldIdizQgSTiClhRDdOOoLErMT4yY0NU+EO4edjKgpLGC8+OG0p6wXoNGXhPfuaTY/4cYEfnO5EW3kJk2T0iMaxhcOpPaz6xcgK6h99pZfzzdUYkyhmKld4Fb3bxULvRrHo13CBxnOlUDid4jn5Ckl1HtsmtdoY4qfUQnJumOj8C92/Zub1J0smVV05yuj8r1OiGk75Q4nTxrkSL19dsrZnd6ZitKrthOr1F7WBb8N913g8lXqgn7APAw=
  file: 
    - bp_linux.tar.gz
    - bp_windows.zip
  on:
    repo: Azure/blobporter
    tags: true 